---
- name: Install MVG Compressor
  hosts: data.mvg.auch.cool
  remote_user: root
  vars_files:
    - vault.yaml

  tasks:
  - name: copy compressor
    template:
      src: "../compressor/{{ item.src }}"
      dest: /srv/compressor/{{ item.dest }}
      mode: a+x
    with_items:
      - src: "compress.sh.j2"
        dest: "compress.sh"
      - src: "compress-messages-mvg.sh.j2"
        dest: "compress-messages-mvg.sh"
      - src: "compress-messages-sbahn.sh.j2"
        dest: "compress-messages-sbahn.sh"

  - name: install service and timer
    copy:
      src: "{{ item }}"
      dest: /etc/systemd/system/
    loop:
      - "../compressor/mvg-compressor.service"
      - "../compressor/mvg-compressor.timer"
  
  - name: start timer
    systemd:
      state: started
      enabled: true
      name: mvg-compressor.timer
      daemon_reload: true